on:
  push:
    branches:
      - main

jobs:
  install:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    environment: Prod

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: ".node-version"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: |
          export VITE_API_URL=https://ping-time.zen56122.workers.dev/
          pnpm build

      - name: Run linter
        run: pnpm lint

      - name: Deploy Frontend
        run: |
          USERNAME=andvarfolomeev
          EMAIL=andreika.varfolomeev@yandex.ru
          REPONAME=ping-time
          cd ./apps/frontend/dist
          ln -s index.html 404.html
          git config --global user.email "$USERNAME"
          git config --global user.name "$EMAIL"
          git init
          git add -A
          git commit -m 'autogenerated'
          git push -f https://${USERNAME}:${{ secrets.GITHUB_TOKEN }}@github.com/${USERNAME}/${REPONAME}.git master:gh-pages
        shell: bash

      - name: Deploy Backend
        run: |
          cd ./apps/backend
          CLOUDFLARE_API_TOKEN=${{ secrets.CLOUDFLARE_API_TOKEN }} pnpm run deploy
